### PR TITLE
Improve filter shortcuts and test

### PR DESCRIPTION
**Pull request by igieon**
- update documentation
- relationship id
- tests

### CODE REVIEW

**Comment by igieon** [comment]
@mahenzon Can you review i found during refactoring that in first case we don't use alias.

**Comment by mahenzon** [comment]
Hi! Will take a look, thanks!

**Review by mahenzon — DISMISSED** [review]
Great, thanks

**Review by mahenzon — APPROVED** [review]
Just rebased. OK

**Pull request merged**
