### PR TITLE
Pagination improvement use dict of ints and expect it everywhere

### PR DESCRIPTION
**Pull request by igieon**
- default PAGE_SIZE can disable pagination only when is requested
- tests

### CODE REVIEW

**Comment by mahenzon** [comment]
Hi! Why do you suggest disabling default pagination?

**Comment by igieon** [comment]
I have request from our PO that for small API we don't need pagination currently pagination can't by disabled with global settings this patch just change this so you can put as default PAGE_SIZE=0.

**Review by mahenzon — APPROVED** [review]
great

**Comment by mahenzon** [comment]
hey, sorry for a delay, it's a good feature. thank you for your contribution!

**Pull request merged**
