### PR TITLE
Update marshmallow_jsonapi version to 0.24.0

### PR DESCRIPTION
**Pull request by ddobson**
Hey there! First let me say thank you for all the awesome improvements and maintenance this team has done with the original code base. My team has chosen to use this fork for a new project, but we quickly noticed that our nested schema validation errors were not correct. After some digging I discovered that the issue was actually with `marshmallow-jsonapi` (see https://github.com/marshmallow-code/marshmallow-jsonapi/issues/120). This PR bumps the version of the dependency with all changes detailed below. Cheers!

This version bump includes:
- 0.24.0 Drop support for marshmallow 2, which is now EOL (https://github.com/marshmallow-code/marshmallow-jsonapi/issues/332). Fix behavior when serializing None (https://github.com/marshmallow-code/marshmallow-jsonapi/issues/302).
- 0.23.2 Import from collections.abc for forward-compatibility with Python 3.10 (https://github.com/marshmallow-code/marshmallow-jsonapi/issues/318)
- 0.23.1 Fix nested fields validation error formatting (https://github.com/marshmallow-code/marshmallow-jsonapi/issues/120)
- 0.23.0 Improve performance of link generation (https://github.com/marshmallow-code/marshmallow-jsonapi/issues/277)

### CODE REVIEW

**Comment by ddobson** [comment]
Just realized that this change has broken the test suite in Travis, however, locally all of my tests are passing on Python 3.7. I will try to dig into the code a bit more when I get a little free time.

**Comment by iamareebjamal** [comment]
0.24.0 should work now

**Review by dmitrymishanov — APPROVED** [review]

**Comment by dmitrymishanov** [comment]
@ddobson Thanks :) 
Merged your PR

**Comment by mahenzon** [comment]
hehe just noticed this

2/4 of fixes are my PR's 🌚 . We needed those fixes at AdCombo too

Thanks for your kind words @ddobson

**Pull request merged**
