### PR TITLE
fix __init_subclass__ for multi project (Flask 2.2)

### PR DESCRIPTION
**Pull request by tarasovdg**

### CODE REVIEW

**Comment by igieon** [comment]
Just question what is reason to move init_subclass from Resource to subclasses ResourceList, ResourceDetail, ResourceRelationship ?

**Comment by tarasovdg** [comment]
When there are several projects in succession, decorators start to accumulate, and incorrect decorators are applied (which were previously added by another project)

**Review by dennyche — APPROVED** [review]

**Comment by igieon** [comment]
> When there are several projects in succession, decorators start to accumulate, and incorrect decorators are applied (which were previously added by another project)

Can you provide example or test where is this problem.

**Comment by igieon** [comment]
@tarasovdg @dennyche  still i don't see problem or why you move code from Resource to ResourceList, ResourceDetail and ResourceRelationship. Can you provide class hierarchy where is this problem ?

**Pull request merged**
