### PR TITLE
Feature to support 'in' clause based on jsonapi filter=1,2,3 - BUG: #189 #190

### PR DESCRIPTION
**Pull request by rubenghio**
This is a simple and quick idea to support "IN" clause based on jsonapi specification:

filter[id]=1,2,3

Hope this helps

### CODE REVIEW

**Comment by Znbiz** [comment]
Hello, @rubenghio
Thanks for contributing to libraries

If the field in the database is of the List type, for example `list_user = db.Column(db.List)`. In this case, we will no longer be able to simply filter out all records that have only 1.3 in the list ...

If you need in, use `filter=[{"name": "id", "op": "in_", "val": [1, 2, 3]}]`

**Comment by mahenzon** [comment]
Please consider providing tests for both cases when it's an array on the backend and when it's an int/str

from #35:

>  I think we have to do it this way: if value on the backend is not a collection type (not an ARRAY), but is an int or str, we should replace `eq` filter with `in_` and parse incoming data as a list, not as a single value.

**Comment by igieon** [comment]
I submit pull request where you can use your custom QueryStringManager with test so you can use change eq and in as it is proposed in this request. Its this pull request #54 . Also in test method `test_sqlalchemy_data_layer.test_get_list_with_simple_filter_relationship_custom_qs`

**Comment by mahenzon** [comment]
looks good

**Pull request merged**
