### PR TITLE
feat: Allow fetching multiple relationships from same included resource

### LINKED ISSUE #39: Allow fetching multiple relationships from same included resource
For example, let's say, we have this resource heirarchy event -> session -> track, location

And I want to fetch them all, my query would be

`/v1/events/123?include=session.track,session.location`

This should be possible, as evident here http://jsonapiplayground.reyesoft.com/v2/stores/1?include=books.author,books.chapters

But the library implementation overrides the previous include by latest include, so it will only include session.location, and not session.track

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #39

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Tests are not working? Do you need help migrating to github actions

**Comment by iamareebjamal** [comment]
@mahenzon Ping

**Comment by mahenzon** [comment]
Hi! Thank you very much for your PR!

Could you please provide some tests, so:
1. we can see that feature actually works
2. we are sure that we don't break it in the next update

**Comment by iamareebjamal** [comment]
For adding tests for the feature, we need 3 levels of relationship. Like event -> session -> speaker,track

We only have 2 levels computer -> person

What relationships should I add on person?

**Comment by mahenzon** [comment]
It doesn't matter here. You can add anything you want. If you don't come up with something for computer + person, just use 'event -> session -> speaker,track'

**Comment by iamareebjamal** [comment]
Yeah, for that I'll have to add event, session, speaker and track model, schema and API etc

Will think of something for existing model graph

**Comment by mahenzon** [comment]
They're already person_tag_model and person_single_tag_model (with different relationship types), you can work on top of this (add smth on top of the person, like 'company - person - tags,single_tag'

**Comment by iamareebjamal** [comment]
They are not relationships but nested attributes, they are already included

I have added address model for a person

**Comment by mahenzon** [comment]
Hmm, is there a way to trigger a new tests run? 🤔 
 and get new coverage report

**Comment by iamareebjamal** [comment]
Don't know how coveralls works, but coverage didn't change as the lines added were already being executed in the previous tests

**Comment by mahenzon** [comment]
coveralls is triggered by Travis build

**Comment by iamareebjamal** [comment]
I cannot see Travis build integration here. And Travis has also stopped its Open Source program, so I don't know how it even worked previously

**Comment by mahenzon** [comment]
hmm, ok, time to migrate to GitHub Actions

**Comment by mahenzon** [comment]
trying to fix it in #42 
I'll ping you when it'll be merged

**Comment by mahenzon** [comment]
pls rebase your branch on master and force-push

**Comment by mahenzon** [comment]
btw travis actually was triggered 15m ago https://travis-ci.org/github/AdCombo/flask-combo-jsonapi/builds/756300126

😅

**Comment by iamareebjamal** [comment]
Done

**Pull request merged**
